server:
  port: 8081
spring:
  graphql:
    schema:
      file-extensions: graphql
    websocket:
      path: graphql
  application:
    name: graphqlpractice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/${RDS_DB}?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: Asia/Seoul
      serialization:
        fail-on-empty-beans: false